import React, { useEffect, useState } from 'react';
import { fetchTodayRecommendations } from '../services/api';
import { Link } from 'react-router-dom';

const Recommendations = () => {
  const [recs, setRecs] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchTodayRecommendations().then(data => {
      setRecs(data);
      setLoading(false);
    });
  }, []);

  if (loading) return <div className="p-6">Loading recommendations...</div>;

  return (
    <div>
      <h1>Daily Recommendations</h1>
      <p>Latest recommendations generated by our AI system based on technical and fundamental analysis.</p>

      <div className="card mt-6">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Date</th>
                <th>Symbol</th>
                <th>Name</th>
                <th>Current Price</th>
                <th>Signal</th>
                <th>Target</th>
                <th>Stop Loss</th>
                <th>Confidence</th>
              </tr>
            </thead>
            <tbody>
              {recs.map((rec, idx) => (
                <tr key={idx}>
                  <td>{rec.date ? new Date(rec.date).toLocaleDateString() : '-'}</td>
                  <td>
                    <Link to={`/stock/${rec.symbol}`} className="font-bold text-accent-primary" style={{textDecoration: 'none'}}>
                      {rec.symbol}
                    </Link>
                  </td>
                  <td>{rec.name}</td>
                  <td>Rp {rec.current_price?.toLocaleString()}</td>
                  <td>
                    <span className={`badge badge-${rec.signal?.toLowerCase()}`}>
                      {rec.signal}
                    </span>
                  </td>
                  <td className="text-green">Rp {rec.target_price?.toLocaleString()}</td>
                  <td className="text-red">Rp {rec.stop_loss?.toLocaleString()}</td>
                  <td>{rec.confidence}%</td>
                </tr>
              ))}
            </tbody>
          </table>
          {recs.length === 0 && <p className="p-4 text-center">No data available.</p>}
        </div>
      </div>
    </div>
  );
};

export default Recommendations;
